spring:
  application:
    name: hms
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

invoice:
  tax-rate: 18
  company:
    name: "Hotel Management"
    email: ${MAIL_ID}
    phone: "+1-800-555-0123"
    address: "123 Hotel Street, City, Country"

logging:
  level:
    root: info
    com:
      vinayakit:
        hms:
          DEBUG

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 8600000